name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
        with:
          project_status: official
          project_stability: alpha
          project_type: other

  test-momento:
    strategy:
      matrix:
        node: [16, 18, 20]
        compression: [true, false]
    name: Test on Node ${{ matrix.node }}
    runs-on: macos-latest
    env:
      MOMENTO_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      CACHE_NAME: js-io-redis-client-test-ci
      COMPRESSION: ${{ matrix.compression }}

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          node -v

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test using a Momento backend
        run: npm run test-momento

  # This is a separate job from than the above because the container services
  # do not run off the shelf on macos. This is a known issue with GitHub Actions.
  test-redis:
    strategy:
      # TODO the redis tests are flaky when run all in parallel.
      max-parallel: 2
      matrix:
        node: [16, 18, 20]
    name: Test on Node ${{ matrix.node }}
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
          - 6379:6379

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          node -v

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test using a Redis backend
        run: npm run test-redis
