name: Build
on:
  pull_request:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Verify README generation
        uses: momentohq/standards-and-practices/github-actions/oss-readme-template@gh-actions-v1
        with:
          project_status: official
          project_stability: alpha
          project_type: other

  test-momento:
    strategy:
      matrix:
        node: [14, 16, 18]
    name: Test on Node ${{ matrix.node }}
    runs-on: macos-latest
    env:
      TEST_AUTH_TOKEN: ${{ secrets.ALPHA_TEST_AUTH_TOKEN }}
      TEST_CACHE_NAME: js-redis-client-test-ci

    steps:
      - name: Setup repo
        uses: actions/checkout@v3

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install dependencies
        run: |
          npm ci
          node -v

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint
